[package]
name = "polkadot-node-core-pvf-common"
description = "Polkadot crate that contains functionality related to PVFs that is shared by the PVF host and the PVF workers."
version = "17.0.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-only"

[lints]
workspace = true

[dependencies]
native = { workspace = true }

cpu-time = "1.0.0"
futures = { workspace = true }
libc = "0.2.172"
nix = { version = "0.28.0", features = ["resource", "sched"] }
thiserror = "1.0.64"

codec = { version = "3.6.12", package = "parity-scale-codec", default-features = false, features = [
 "derive",
] }
gum = { version = "17.0.0", package = "tracing-gum", default-features = true }
polkadot-parachain-primitives.workspace = true
polkadot-parachain-primitives.default-features = true
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
sc-executor.workspace = true
sc-executor.default-features = true
sc-executor-common = { version = "0.36.0", default-features = true }
sc-executor-wasmtime = { version = "0.36.0", default-features = true }
sp-core.workspace = true
sp-core.default-features = true
sp-crypto-hashing = { version = "0.1.0", default-features = true }
sp-externalities = { version = "0.30.0", default-features = true }
sp-io.workspace = true
sp-io.default-features = true
sp-tracing = { version = "17.0.1", default-features = true }

[target.'cfg(target_os = "linux")'.dependencies]
landlock = "0.3.0"

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
seccompiler = "0.4.0"

[dev-dependencies]
assert_matches = "1.5.0"

[target.'cfg(target_os = "linux")'.dev-dependencies]
tempfile = { workspace = true }

[features]
# This feature is used to export test code to other crates without putting it in the production build.
test-utils = []
jemalloc-allocator = []
