[package]
name = "pallet-tee-verifier"
version = "0.1.0"
description = "A tee verifier pallet implementation based on pallet-verifiers abstraction."
homepage.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
codec = { workspace = true }
hex-literal = { workspace = true, optional = true }
scale-info = { workspace = true }
hp-verifiers = { workspace = true }
log = { workspace = true }
pallet-verifiers = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true, optional = true }
tee-verifier = { workspace = true }
pallet-crl = { workspace = true }
serde-json-core = { workspace = true }
chrono = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-babe = { workspace = true }
sp-consensus-babe = { workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true }
hex-literal = { workspace = true }

[features]
default = [ "std" ]
std = [
	"chrono/std",
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"hp-verifiers/std",
	"log/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-crl/std",
	"pallet-timestamp/std",
	"pallet-verifiers/std",
	"scale-info/std",
	"serde-json-core/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-io?/std",
	"tee-verifier/std",
]
runtime-benchmarks = [
	"dep:frame-benchmarking",
	"dep:hex-literal",
	"dep:sp-io",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-verifiers/runtime-benchmarks",
]
